/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BuscarClienteForm.java
 *
 * Created on Mar 28, 2010, 9:04:07 AM
 */

package com.agac.gui;

import com.agac.bo.Receptor;
import com.agac.services.DbServices;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author alex
 */
public class BuscarClienteForm extends javax.swing.JPanel {

    /** Creates new form BuscarClienteForm */
    public BuscarClienteForm() {
        initComponents();
        txtBusqueda.requestFocus();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rdbRfc = new javax.swing.JRadioButton();
        rdbNombre = new javax.swing.JRadioButton();
        txtBusqueda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstResults = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();

        buttonGroup1.add(rdbRfc);
        rdbRfc.setText(org.openide.util.NbBundle.getMessage(BuscarClienteForm.class, "BuscarClienteForm.rdbRfc.text")); // NOI18N

        buttonGroup1.add(rdbNombre);
        rdbNombre.setSelected(true);
        rdbNombre.setText(org.openide.util.NbBundle.getMessage(BuscarClienteForm.class, "BuscarClienteForm.rdbNombre.text")); // NOI18N

        txtBusqueda.setText(org.openide.util.NbBundle.getMessage(BuscarClienteForm.class, "BuscarClienteForm.txtBusqueda.text")); // NOI18N

        lstResults.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstResultsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstResults);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/agac/gui/resourses/find.png"))); // NOI18N
        jButton1.setText(org.openide.util.NbBundle.getMessage(BuscarClienteForm.class, "BuscarClienteForm.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdbRfc)
                            .addComponent(rdbNombre))
                        .addGap(18, 18, 18)
                        .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(rdbRfc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdbNombre))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String qry = "";
        List<Receptor> results = null;
        if(rdbRfc.isSelected()){
            qry = "Select r from Receptor r where UPPER(r.rfc) like ?1 order by r.nombre";
            results = DbServices.getListWithParameters(qry, "%" + txtBusqueda.getText().toUpperCase() + "%");
        }else{
            qry = "Select r from Receptor r where UPPER(r.nombre) like ?1 order by r.nombre";
            results = DbServices.getListWithParameters(qry, "%" + txtBusqueda.getText().toUpperCase() + "%");
        }
        DefaultListModel model = new DefaultListModel();
        for(Receptor r : results){
            model.addElement(r);
        }
        lstResults.setModel(model);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lstResultsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstResultsValueChanged
        receptor  = (Receptor)((JList)evt.getSource()).getSelectedValue();
    }//GEN-LAST:event_lstResultsValueChanged

    private Receptor receptor;

    public Receptor getReceptor() {
        return receptor;
    }

    public void setReceptor(Receptor receptor) {
        this.receptor = receptor;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstResults;
    private javax.swing.JRadioButton rdbNombre;
    private javax.swing.JRadioButton rdbRfc;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables

}
