/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PartesPanel.java
 *
 * Created on Mar 13, 2010, 8:53:14 AM
 */
package com.agac.gui;

import com.agac.bo.Concepto;
import com.agac.bo.InformacionAduanera;
import com.agac.bo.Parte;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import org.openide.DialogDescriptor;
import org.openide.DialogDisplayer;
import org.openide.NotifyDescriptor;
import org.openide.NotifyDescriptor.Message;

/**
 *
 * @author Carlos
 */
public class PartesPanel extends javax.swing.JPanel {

    /** Creates new form PartesPanel */
    public PartesPanel() {
        initComponents();

        txtCantidad.getDocument().addDocumentListener(listenCantidad);
        txtPrecio.getDocument().addDocumentListener(listenPrecio);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        txtCantidad = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        txtIdentificador = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${parte.cantidad}"), txtCantidad, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        txtCantidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCantidadFocusLost(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pieza", "Caja", "Consumo", "Gramos", "Kilos", "Litros", "Mililitros", "Paquete", "Servicio" }));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${parte.unidad}"), jComboBox1, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${parte.noIdentificacion}"), txtIdentificador, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${parte.descripcion}"), txtDescripcion, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${parte.valorUnitario}"), txtPrecio, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        txtPrecio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPrecioFocusLost(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/agac/gui/resourses/add.png"))); // NOI18N
        jButton4.setText(org.openide.util.NbBundle.getMessage(PartesPanel.class, "PartesPanel.jButton4.text")); // NOI18N
        jButton4.setMaximumSize(new java.awt.Dimension(49, 20));
        jButton4.setMinimumSize(new java.awt.Dimension(49, 20));
        jButton4.setPreferredSize(new java.awt.Dimension(49, 20));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton4KeyPressed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cantidad", "Unidad", "Identificador", "Descripción", "Precio", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText(org.openide.util.NbBundle.getMessage(PartesPanel.class, "PartesPanel.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel16.setText(org.openide.util.NbBundle.getMessage(PartesPanel.class, "PartesPanel.jLabel16.text")); // NOI18N

        jLabel15.setText(org.openide.util.NbBundle.getMessage(PartesPanel.class, "PartesPanel.jLabel15.text")); // NOI18N

        jLabel14.setText(org.openide.util.NbBundle.getMessage(PartesPanel.class, "PartesPanel.jLabel14.text")); // NOI18N

        jLabel13.setText(org.openide.util.NbBundle.getMessage(PartesPanel.class, "PartesPanel.jLabel13.text")); // NOI18N

        jLabel12.setText(org.openide.util.NbBundle.getMessage(PartesPanel.class, "PartesPanel.jLabel12.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addGap(36, 36, 36)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(txtIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(jLabel15))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 300, Short.MAX_VALUE)
                                .addComponent(jLabel16)
                                .addGap(77, 77, 77)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCantidad)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtIdentificador, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        //if (validaCampos()) {

        try {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            Object[] row = new Object[6];
            parte.setUnidad(jComboBox1.getSelectedItem().toString());
            row[0] = parte.getCantidad();
            row[1] = parte.getUnidad();
            row[2] = parte.getDescripcion();
            row[3] = parte.getNoIdentificacion();
            row[4] = parte.getValorUnitario();
            row[5] = parte.getImporte();
            model.addRow(row);
            txtCantidad.setText("");
            txtDescripcion.setText("");
            txtIdentificador.setText("");
            txtPrecio.setText("");
            txtCantidad.requestFocus();
            concepto.getParte().add(parte);
            parte = new Parte();
        } catch  (Exception e) {
            Message msg = new NotifyDescriptor.Message("Algún dato podría faltar ó tener formato erroneo!!");
            Object notify = DialogDisplayer.getDefault().notify(msg);

        }
}//GEN-LAST:event_jButton4ActionPerformed

    private void jButton4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton4KeyPressed
}//GEN-LAST:event_jButton4KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        List<InformacionAduanera> infoAduanera = new ArrayList<InformacionAduanera>();
        if (concepto.getInfoAduanera() != null) {
            infoAduanera.addAll(parte.getInfoAduanera());
        }
        InformacionAduaneraPanel infPanel = new InformacionAduaneraPanel();
        infPanel.setInfoAduaneraList(infoAduanera);
        DialogDescriptor dd = new DialogDescriptor(infPanel,
                "Información Aduanera", true, null);
        Object result = DialogDisplayer.getDefault().notify(dd);
        if (NotifyDescriptor.OK_OPTION.equals(result)) {
            parte.setInfoAduanera(infoAduanera);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCantidadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidadFocusLost
        // TODO add your handling code here:

        listenCantidad.insertUpdate(null);

    }//GEN-LAST:event_txtCantidadFocusLost

    private void txtPrecioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrecioFocusLost
        // TODO add your handling code here:

        listenPrecio.insertUpdate(null);
    }//GEN-LAST:event_txtPrecioFocusLost
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtIdentificador;
    private javax.swing.JTextField txtPrecio;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    private Concepto concepto = new Concepto();

    public Concepto getConcepto() {
        return concepto;
    }

    public void setConcepto(Concepto concepto) {
        this.concepto = concepto;
        for (Parte p : concepto.getParte()) {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            Vector row = new Vector();
            row.add(p.getCantidad());
            row.add(p.getUnidad());
            row.add(p.getDescripcion());
            row.add(p.getNoIdentificacion());
            row.add(p.getValorUnitario());
            row.add(p.getImporte());
            model.addRow(row);
        }
    }
    private Parte parte = new Parte();

    public Parte getParte() {
        return parte;
    }

    public void setParte(Parte parte) {
        this.parte = parte;
    }
    DocumentListener listenCantidad = new DocumentListener() {

        @Override
        public void insertUpdate(DocumentEvent event) {
            validar();
        }

        @Override
        public void removeUpdate(DocumentEvent event) {
            validar();
        }

        @Override
        public void changedUpdate(DocumentEvent event) {
        }

        public void validar() {
            try {
                Double test = Double.parseDouble(txtCantidad.getText().trim());

                //Tampoco se valen cantidades negativas
                if (test < 0) {
                    throw (new NumberFormatException());
                }


                txtCantidad.setForeground(Color.black);
                txtCantidad.setFont(txtCantidad.getFont().deriveFont(Font.PLAIN));
                jButton4.setEnabled(true);
            } catch (NumberFormatException e) {

                //txtCantidad.requestFocus();
                txtCantidad.setForeground(Color.red);
                txtCantidad.setFont(txtCantidad.getFont().deriveFont(Font.BOLD));
                jButton4.setEnabled(false);
            }
        }
    };
    DocumentListener listenPrecio = new DocumentListener() {

        @Override
        public void insertUpdate(DocumentEvent event) {
            validar();
        }

        @Override
        public void removeUpdate(DocumentEvent event) {
            validar();
        }

        @Override
        public void changedUpdate(DocumentEvent event) {
        }

        public void validar() {
            try {
                Double test = Double.parseDouble(txtPrecio.getText().trim());

                //Tampoco se valen precios negativos
                if (test < 0) {
                    throw (new NumberFormatException());
                }


                txtPrecio.setForeground(Color.black);
                txtPrecio.setFont(txtPrecio.getFont().deriveFont(Font.PLAIN));
                jButton4.setEnabled(true);
            } catch (NumberFormatException e) {

                //txtPrecio.requestFocus();
                txtPrecio.setForeground(Color.red);
                txtPrecio.setFont(txtPrecio.getFont().deriveFont(Font.BOLD));
                jButton4.setEnabled(false);
            }
        }
    };

    private boolean validaCampos() {

        if (txtDescripcion.getText().trim().equals("")) {
            return false;
        } else {
            return true;
        }
    }
}
