/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ReporteMensualPanel.java
 *
 * Created on May 10, 2010, 8:40:40 PM
 */

package com.agac.gui;

import com.agac.bo.Emisor;
import java.awt.FileDialog;
import org.openide.windows.WindowManager;

/**
 *
 * @author alex
 */
public class ReporteMensualPanel extends javax.swing.JPanel {

    /** Creates new form ReporteMensualPanel */
    public ReporteMensualPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboMes = new javax.swing.JComboBox();
        cboAno = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtRuta = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnGenerar = new javax.swing.JButton();

        setToolTipText(org.openide.util.NbBundle.getMessage(ReporteMensualPanel.class, "ReporteMensualPanel.toolTipText")); // NOI18N

        jLabel1.setText(org.openide.util.NbBundle.getMessage(ReporteMensualPanel.class, "ReporteMensualPanel.jLabel1.text")); // NOI18N

        cboMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        cboAno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2010", "2011", "2012", "2013", "2014", "2015" }));

        jLabel2.setText(org.openide.util.NbBundle.getMessage(ReporteMensualPanel.class, "ReporteMensualPanel.jLabel2.text")); // NOI18N

        txtRuta.setText(org.openide.util.NbBundle.getMessage(ReporteMensualPanel.class, "ReporteMensualPanel.txtRuta.text")); // NOI18N

        btnBuscar.setText(org.openide.util.NbBundle.getMessage(ReporteMensualPanel.class, "ReporteMensualPanel.btnBuscar.text")); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnGenerar.setText(org.openide.util.NbBundle.getMessage(ReporteMensualPanel.class, "ReporteMensualPanel.btnGenerar.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtRuta, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cboMes, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscar, 0, 0, Short.MAX_VALUE)
                    .addComponent(cboAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGenerar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:

        FileDialog fd = new FileDialog(WindowManager.getDefault().getMainWindow(),
                "Archivo de reporte", FileDialog.SAVE);
        fd.setFile("*.txt");
        fd.setVisible(true);



        txtRuta.setText( fd.getDirectory() + "1"+ emisor.getRfc() + mesAnumero() + cboAno.getSelectedItem().toString() + ".txt");


       // if (fd.getFile() != null) {
       //     txtCer.setText(fd.getDirectory() + fd.getFile());
       //     certOK = true;
       // }



    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JComboBox cboAno;
    private javax.swing.JComboBox cboMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtRuta;
    // End of variables declaration//GEN-END:variables


    private Emisor emisor = new Emisor();

    public Emisor getEmisor() {
        return emisor;
    }

    public void setEmisor(Emisor emisor) {
        this.emisor = emisor;
    }


    public String mesAnumero(){
        String mes = "";
        if(cboMes.getSelectedIndex() == 0) mes = "01";
        if(cboMes.getSelectedIndex() == 1) mes = "02";
        if(cboMes.getSelectedIndex() == 2) mes = "03";
        if(cboMes.getSelectedIndex() == 3) mes = "04";
        if(cboMes.getSelectedIndex() == 4) mes = "05";
        if(cboMes.getSelectedIndex() == 5) mes = "06";
        if(cboMes.getSelectedIndex() == 6) mes = "07";
        if(cboMes.getSelectedIndex() == 7) mes = "08";
        if(cboMes.getSelectedIndex() == 8) mes = "09";
        if(cboMes.getSelectedIndex() == 9) mes = "10";
        if(cboMes.getSelectedIndex() == 10) mes = "11";
        if(cboMes.getSelectedIndex() == 11) mes = "12";

        return mes;

    }


}
