'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Informe

    '''<summary>
    '''menu_items control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents menu_items As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''menu_item_admin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents menu_item_admin As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''cld_bg_inicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cld_bg_inicio As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''cld_selector_inicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cld_selector_inicio As Global.System.Web.UI.WebControls.Calendar

    '''<summary>
    '''cld_bg_final control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cld_bg_final As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''cld_selector_final control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cld_selector_final As Global.System.Web.UI.WebControls.Calendar

    '''<summary>
    '''grp_informe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grp_informe As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnl_club control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_club As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''labelClub control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents labelClub As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''club control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents club As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''v_club control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents v_club As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''pnl_periodo_inicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_periodo_inicio As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_periodo_inicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_periodo_inicio As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tb_periodo_inicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_periodo_inicio As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''v_tb_periodo_inicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents v_tb_periodo_inicio As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''btn_periodo_inicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_periodo_inicio As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnl_periodo_final control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_periodo_final As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_periodo_final control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_periodo_final As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tb_periodo_final control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_periodo_final As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''v_tb_periodo_final control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents v_tb_periodo_final As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''btn_peridodo_final control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_peridodo_final As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnl_tipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_tipo As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_tipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_tipo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddl_tipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_tipo As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''v_ddl_tipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents v_ddl_tipo As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''pnl_informe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_informe As Global.System.Web.UI.WebControls.Panel
End Class
