'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Cambio1

    '''<summary>
    '''Form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''grp_busqueda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grp_busqueda As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnl_busqueda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_busqueda As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_busqueda_nombre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_busqueda_nombre As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tb_busqueda_nombre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_busqueda_nombre As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_busqueda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_busqueda As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnl_resultados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_resultados As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''dg_resultados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dg_resultados As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''grp_consultar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grp_consultar As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnl_consultar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_consultar As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_consultar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_consultar As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tb_consultar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_consultar As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RequiredFieldValidator4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator4 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''btn_consultar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_consultar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_consultar_popup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_consultar_popup As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''grp_modificar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grp_modificar As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnl_club control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_club As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_club control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_club As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''club control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents club As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''pnl_seleccionar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_seleccionar As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnl_nombre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_nombre As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_nombre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_nombre As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tb_nombre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_nombre As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnl_apaterno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_apaterno As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_apaterno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_apaterno As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tb_apaterno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_apaterno As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnl_amaterno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_amaterno As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_amaterno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_amaterno As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tb_amaterno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_amaterno As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnl_cumpleanos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_cumpleanos As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_cumpleanos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_cumpleanos As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddl_cump_dia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_cump_dia As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddl_cump_mes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_cump_mes As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddl_cump_ano control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_cump_ano As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''pnl_telefono control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_telefono As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_telefono control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_telefono As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tb_telefono control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_telefono As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnl_ciudad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_ciudad As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_ciudad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_ciudad As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tb_ciudad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_ciudad As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnl_correo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_correo As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_correo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_correo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tb_correo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_correo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnl_rfc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_rfc As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_rfc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_rfc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tb_rfc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_rfc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnl_compania control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_compania As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_compania control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_compania As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddl_compania control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_compania As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''pnl_tarifa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_tarifa As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_tarifa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_tarifa As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tb_tarifa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_tarifa As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnl_agencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_agencia As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_agencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_agencia As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tb_agencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_agencia As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnl_modificar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_modificar As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btn_modificar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_modificar As Global.System.Web.UI.WebControls.Button
End Class
